# Generated by Django 5.0 on 2024-08-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='serial',
            field=models.IntegerField(default=0),
        ),
    ]
