# Generated by Django 5.0 on 2024-08-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_control', '0002_boardmodel_serial_cardmodel_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
