# Generated by Django 5.0 on 2024-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_control', '0003_alter_boardmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
