# Generated by Django 5.1 on 2024-08-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_requestlog_contactusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerModel',
        ),
    ]
