# Generated by Django 5.0 on 2024-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembermodel',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Member', 'Member')], default='Member', max_length=255),
        ),
    ]
