# Generated by Django 5.0 on 2024-09-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_control', '0002_alter_workspacemembermodel_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='workspacemembermodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Workspace Member', 'verbose_name_plural': 'Workspace Members'},
        ),
        migrations.AlterModelOptions(
            name='workspacemodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
