# Generated by Django 5.0 on 2024-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_control', '0003_alter_projectmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemodel',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
